# Generated by Django 4.0.4 on 2022-11-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Kids', 'Kids'), ('Mens', 'Mens'), ('Women', 'Women')], default='none', max_length=5),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='media/product_images'),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
