# Generated by Django 4.0.4 on 2022-11-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0003_trial_alter_products_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('Id', models.AutoField(default=1001, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('Mobile', models.IntegerField()),
                ('ShopName', models.CharField(max_length=200)),
                ('VerificationStatus', models.CharField(choices=[('Verified', 'Verified'), ('Not Verified', 'Not Verified')], default='Not Verified', max_length=50)),
            ],
        ),
    ]
