# Generated by Django 4.0.4 on 2022-11-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0004_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='VerificationDocument',
            field=models.ImageField(default='', upload_to='seller_documents'),
        ),
    ]
