# Generated by Django 4.0.4 on 2022-11-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0005_seller_verificationdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller_id', models.IntegerField()),
                ('Customer_id', models.IntegerField()),
                ('Order_id', models.CharField(max_length=200)),
                ('Payment_id', models.CharField(max_length=200)),
                ('Signature', models.CharField(max_length=200)),
                ('Amount', models.IntegerField()),
                ('Status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed')], default='Failed', max_length=50)),
            ],
        ),
    ]
