# Generated by Django 4.0.4 on 2022-11-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0006_paymentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('prod_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='listedBy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.CharField(choices=[('Summer', 'Summer'), ('Winter', 'Winter')], default='none', max_length=10),
        ),
    ]
