# Generated by Django 4.0.4 on 2022-12-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0008_cart_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='listedBy',
            field=models.IntegerField(default=0),
        ),
    ]
