# Generated by Django 4.0.4 on 2022-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0009_cart_listedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
