# Generated by Django 4.0.4 on 2022-12-03 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0011_alter_cart_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='desc',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
