# Generated by Django 4.0.4 on 2022-12-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0012_cart_desc_cart_price_cart_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='image',
            field=models.ImageField(default='', upload_to='product_images'),
        ),
    ]
