# Generated by Django 4.0.4 on 2022-12-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0015_alter_cart_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
