# Generated by Django 4.0.4 on 2022-12-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0016_remove_cart_desc_remove_cart_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='Month',
            field=models.IntegerField(default=0),
        ),
    ]
