# Generated by Django 4.0.4 on 2022-12-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0017_paymentdetails_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellerId', models.IntegerField(default=0)),
                ('sales', models.IntegerField(default=0)),
                ('month', models.IntegerField(default=0)),
            ],
        ),
    ]
