# Generated by Django 4.0.4 on 2022-12-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0018_sellersales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trial',
        ),
        migrations.AddField(
            model_name='cart',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='cart',
            name='sub_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
