# Generated by Django 4.0.4 on 2022-12-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0019_delete_trial_cart_category_cart_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellersales',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sellersales',
            name='sub_category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
