# Generated by Django 4.0.4 on 2022-12-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0020_sellersales_category_sellersales_sub_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
