# Generated by Django 4.0.4 on 2022-12-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0022_seller_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='currSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.IntegerField()),
            ],
        ),
    ]
