# Generated by Django 4.0.4 on 2022-12-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0023_currseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='currseller',
            name='s_no',
            field=models.IntegerField(default=1),
        ),
    ]
