# Generated by Django 4.0.4 on 2022-12-15 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0025_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Dispatched', 'Dispatched'), ('Packed', 'Packed'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Dispatched', max_length=50),
        ),
    ]
