# Generated by Django 4.0.4 on 2022-12-16 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0027_alter_orderstatus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='listedBy',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='prod_id',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='title',
        ),
        migrations.RemoveField(
            model_name='orderstatus',
            name='user_id',
        ),
    ]
