# Generated by Django 4.0.4 on 2022-12-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onestop', '0028_remove_orderstatus_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatus',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='listedBy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='prod_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Dispatched', 'Dispatched'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], default='Packed', max_length=50),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderstatus',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
